xquery version "1.0-ml";
module namespace srcHasETTgt-from-srcHasETSrc
    = "http://marklogic.com/srcHasETTgtDsnt/srcHasETTgt-0.0.2-from-srcHasETSrc-0.0.1";

import module namespace es = "http://marklogic.com/entity-services"
    at "/MarkLogic/entity-services/entity-services.xqy";

declare option xdmp:mapping "false";

(:
 This module was generated by MarkLogic Entity Services.
 Its purpose is to create instances of entity types
 defined in
 srcHasETTgt, version 0.0.2
 from documents that were persisted according to model
 srcHasETSrc, version 0.0.1

 Modification History:
 Generated at timestamp: 2016-11-16T00:42:39.053158-08:00
 Persisted by AUTHOR
 Date: DATE

 Target Model srcHasETTgt-0.0.2 Info:

 Type Customer: 
    primaryKey: CustomerID, ( in source: CustomerID )
    required: None, ( in source: None )
    range indexes: None, ( in source: None )
    word lexicons: None, ( in source: None )
 
 Type Product: 
    Removed Type
 
:)


(:~
 : Creates a map:map instance representation of the target
 : entity type Customer from a document that
 : contains the source entity instance.
 : @param $source-node  A document or node that contains data conforming to the
 : source entity type
 : @return A map:map instance that holds the data for this entity type.
 :)

declare function srcHasETTgt-from-srcHasETSrc:convert-instance-Customer(
    $source as node()
) as map:map
{
    let $source-node := srcHasETTgt-from-srcHasETSrc:init-source($source, 'Customer')

    return
    json:object()
    =>srcHasETTgt-from-srcHasETSrc:copy-attachments($source-node)
    (: The following line identifies the type of this instance.  Do not change it. :)
    =>map:with('$type', 'Customer')
    (: The following lines are generated from the 'Customer' entity type. :)
    =>   map:with('CustomerID',             xs:string($source-node/CustomerID))
    =>es:optional('CompanyName',            xs:string($source-node/CompanyName))
    =>es:optional('Country',                xs:string($source-node/Country))
    =>es:optional('ContactName',            xs:string($source-node/ContactName))

};
    
(:
 Entity type Product is in source document
 but not in target document.
 The following XPath expressions should get values from the source
 instances but there is no specified target.
 This comment can be as a starting point for writing a custom
 version converter.

declare function srcHasETTgt-from-srcHasETSrc:convert-instance-Product(
    $source-node as node()
) as map:map
{
    json:object()
    =>map:with('$type', 'Product')
    =>   map:with('ProductName',            xs:string($source-node/ProductName))
    =>es:optional('UnitPrice',              xs:integer($source-node/UnitPrice))
    =>es:optional('SupplierID',             xs:integer($source-node/SupplierID))
:)



declare private function srcHasETTgt-from-srcHasETSrc:init-source(
    $source as node()*,
    $entity-type-name as xs:string
) as node()*
{
    if ( ($source//es:instance/element()[node-name(.) eq xs:QName($entity-type-name)]))
    then $source//es:instance/element()[node-name(.) eq xs:QName($entity-type-name)]
    else $source
};


declare private function srcHasETTgt-from-srcHasETSrc:copy-attachments(
    $instance as json:object,
    $source as node()*
) as json:object
{
    $instance
    =>es:optional('$attachments',
        $source ! fn:root(.)/es:envelope/es:attachments/node())
};