xquery version "1.0-ml";
module namespace tgtHasETTgt-from-tgtHasETSrc
    = "http://marklogic.com/tgtHasETSrcDsnt/tgtHasETTgt-0.0.2-from-tgtHasETSrc-0.0.1";

import module namespace es = "http://marklogic.com/entity-services"
    at "/MarkLogic/entity-services/entity-services.xqy";

declare option xdmp:mapping "false";

(:
 This module was generated by MarkLogic Entity Services.
 Its purpose is to create instances of entity types
 defined in
 tgtHasETTgt, version 0.0.2
 from documents that were persisted according to model
 tgtHasETSrc, version 0.0.1

 Modification History:
 Generated at timestamp: 2016-11-16T00:46:14.087972-08:00
 Persisted by AUTHOR
 Date: DATE

 Target Model tgtHasETTgt-0.0.2 Info:

 Type Customer: 
    primaryKey: CustomerID, ( in source: CustomerID )
    required: None, ( in source: None )
    range indexes: None, ( in source: None )
    word lexicons: None, ( in source: None )
 
 Type Product: 
    missing from source model.
    primaryKey: ProductName, ( in source: None )
    required: None, ( in source: None )
    range indexes: None, ( in source: None )
    word lexicons: None, ( in source: None )
 
:)


(:~
 : Creates a map:map instance representation of the target
 : entity type Customer from a document that
 : contains the source entity instance.
 : @param $source-node  A document or node that contains data conforming to the
 : source entity type
 : @return A map:map instance that holds the data for this entity type.
 :)

declare function tgtHasETTgt-from-tgtHasETSrc:convert-instance-Customer(
    $source as node()
) as map:map
{
    let $source-node := tgtHasETTgt-from-tgtHasETSrc:init-source($source, 'Customer')

    return
    json:object()
    =>tgtHasETTgt-from-tgtHasETSrc:copy-attachments($source-node)
    (: The following line identifies the type of this instance.  Do not change it. :)
    =>map:with('$type', 'Customer')
    (: The following lines are generated from the 'Customer' entity type. :)
    =>   map:with('CustomerID',             xs:string($source-node/CustomerID))
    =>es:optional('CompanyName',            xs:string($source-node/CompanyName))
    =>es:optional('Country',                xs:string($source-node/Country))
    =>es:optional('ContactName',            xs:string($source-node/ContactName))

};
    
(:~
 : Creates a map:map instance representation of the target
 : entity type Product from a document that
 : contains the source entity instance.
 : @param $source-node  A document or node that contains data conforming to the
 : source entity type
 : @return A map:map instance that holds the data for this entity type.
 :)

(: Type Product is not in the source model.
 : XPath expressions are created as though there were no change between source and target type.
 :)
declare function tgtHasETTgt-from-tgtHasETSrc:convert-instance-Product(
    $source as node()
) as map:map
{
    let $source-node := tgtHasETTgt-from-tgtHasETSrc:init-source($source, 'Product')

    return
    json:object()
    =>tgtHasETTgt-from-tgtHasETSrc:copy-attachments($source-node)
    (: The following line identifies the type of this instance.  Do not change it. :)
    =>map:with('$type', 'Product')
    (: The following lines are generated from the 'Product' entity type. :)
    =>   map:with('ProductName',            xs:string($source-node/ProductName))
    =>es:optional('UnitPrice',              xs:integer($source-node/UnitPrice))
    =>es:optional('SupplierID',             xs:integer($source-node/SupplierID))
    =>es:optional('Discontinued',           xs:boolean($source-node/Discontinued))

};
    


declare private function tgtHasETTgt-from-tgtHasETSrc:init-source(
    $source as node()*,
    $entity-type-name as xs:string
) as node()*
{
    if ( ($source//es:instance/element()[node-name(.) eq xs:QName($entity-type-name)]))
    then $source//es:instance/element()[node-name(.) eq xs:QName($entity-type-name)]
    else $source
};


declare private function tgtHasETTgt-from-tgtHasETSrc:copy-attachments(
    $instance as json:object,
    $source as node()*
) as json:object
{
    $instance
    =>es:optional('$attachments',
        $source ! fn:root(.)/es:envelope/es:attachments/node())
};